### PR TITLE
update apk of "Poweroffalarm" Android 12 from ginkgo

### PR DESCRIPTION
**Pull request by odmfl**
With this apk, power off alarm finally works on rom with Android 12.

### CODE REVIEW

**Comment by xenxynon** [comment]
> With this apk, power off alarm finally works on rom with Android 12.

Well if you say
But fix commit message

**Comment by odmfl** [comment]
yes I have tested it and it works, how should I change the message?

**Comment by odmfl** [comment]
the apk was taken here:

https://github.com/trinket-devs/vendor_xiaomi_ginkgo/tree/11.0/proprietary/product/app/PowerOffAlarm

**Comment by xenxynon** [comment]
> yes I have tested it and it works, how should I change the message?

Force push 

> the apk was taken here:
> 
> https://github.com/trinket-devs/vendor_xiaomi_ginkgo/tree/11.0/proprietary/product/app/PowerOffAlarm

Change > Force Push the commit
And well I might suggest to give authorship to @ghostrider-reborn

**Pull request merged**
